import './js/config';
import './js/all-info-API';
import './js/authentication-modal';
import './js/authorization-modal';
import './js/film-info-modal';
import './js/firebase-author-authen-API';
// import './js/firebase-save-films-API';
import './js/film-search-header';
import './js/pagination';
import './js/popular-film-API';
import './js/youtube-info-API';
import './js/trailer-modal';
import './js/team-modal';
