import './js/config';
// import './js/upcoming-films';
import './js/all-info-API';
import './js/authentication-modal';
import './js/authorization-modal';
import './js/firebase-author-authen-API';
import './js/film-search-header';
import './js/pagination';
import './js/popular-film-API';
import './js/youtube-info-API';
import './js/trailer-modal';
import './js/team-modal';
import './js/BtnScrollToTop';
// import './js/film-info-modal';
